model:
  image_size: 128
  use_batchnorm: false
  load_from_checkpoint: false

training:
  batch_size: 8
  learning_rate: 1e-5
  num_epochs: 100
  checkpoint_dir: "./checkpoints"
  checkpoint_name: "best_models.keras"
  log_dir: "./logs"

dataset:
  labelmap_path: "/home/salwa/Documents/code/unet/data/pascalvoc_subset/labelmap_classification.json"
  train_image_path: "/home/salwa/Documents/code/unet/data/pascalvoc_subset/train_image_paths.txt"
  test_image_path: "/home/salwa/Documents/code/unet/data/pascalvoc_subset/train_image_paths.txt"
  test_image: ""